### PR TITLE
Msg reset cmd/tao luke

### PR DESCRIPTION
**Pull request by tao-luke**
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_sensor/3)

### CODE REVIEW

**Comment by tao-luke** [comment]
The new commit to adding support for magnetometer/gyroscope and accelerometer differentiation  has been tested with the changes here:
https://github.com/waterloo-rocketry/canlib/pull/41
https://github.com/waterloo-rocketry/omnibus/pull/58

**Review by KavinSatheeskumar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_sensor/3)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @BluCodeGH and @tao-luke)

___
*[`main.c` line 101 at r2](https://reviewable.io/reviews/waterloo-rocketry/cansw_sensor/3#-N3W2hM-2tb-mF_kNEdq:-N3W2hM-2tb-mF_kNEdr:b-fxaesk) ([raw file](https://github.com/waterloo-rocketry/cansw_sensor/blob/751452830371621bfca661694b96f21d730995b1/main.c#L101)):*
> ```C
>         }
> 
>         if (millis() - last_baro_millis > MAX_LOOP_SENSOR_TIME_DIFF_ms) {
> ```

Kinda dumbass question, but is there any reason we are doing "last_baro_millis" and "last_accel_millis" if the code is going to function identically for all of them?



_Code snippet:_
```C
uint32_t last_millis = millis();
uint32_t last_baro_millis = millis();
uint32_t last_accel_millis = millis();
uint32_t last_accel2_millis = millis();
```
___
*[`main.c` line 116 at r2](https://reviewable.io/reviews/waterloo-rocketry/cansw_sensor/3#-N3W-IXF1ERTwAEDDu-m:-N3W-IXF1ERTwAEDDu-n:b-c07euv) ([raw file](https://github.com/waterloo-rocketry/cansw_sensor/blob/751452830371621bfca661694b96f21d730995b1/main.c#L116)):*
> ```C
>             lsm303_get_accel_raw(accelData, accelData + 1, accelData + 2);
> 
>             int16_t magData[3];
> ```

Took me a while to figure out that this was Magnetometer data. Might be worth a comment either here or somewhere else.



_Code quote:_
```C
lsm303_get_mag_raw
```
___
*[`main.c` line 127 at r2](https://reviewable.io/reviews/waterloo-rocketry/cansw_sensor/3#-N3W1-B3-RdjY44ayFU2:-N3W0_Xz43_Q8-Lhqhem:b8agbxb) ([raw file](https://github.com/waterloo-rocketry/cansw_sensor/blob/751452830371621bfca661694b96f21d730995b1/main.c#L127)):*
> ```C
>             txb_enqueue(&imu_msg2);
>         }
>         if (millis() - last_accel2_millis > MAX_LOOP_SENSOR_TIME_DIFF_ms) {
> ```

If we are changing this if-statement to send gyro-data as well as acceleration data, maybe we had ought change the name "last_accel2_millis" to something like "last_MPU_millis"
___
*[`main.c` line 137 at r2](https://reviewable.io/reviews/waterloo-rocketry/cansw_sensor/3#-N3W18bY5xDOXCvBm9Z3:-N3W18bY5xDOXCvBm9Z4:bsokqhc) ([raw file](https://github.com/waterloo-rocketry/cansw_sensor/blob/751452830371621bfca661694b96f21d730995b1/main.c#L137)):*
> ```C
>             can_msg_t imu_msg;
>             can_msg_t imu_msg2;
>             build_imu_data_msg(MSG_SENSOR_ACC2, millis(), accelData, &imu_msg);
> ```

I know this will be kinda a bitch to change, but maybe MSG_SENSOR_ACC2 had ought be "MSG_SENSOR_MCU_ACC" instead. If we are feeling terribly bitchy, then possibly change MSG_SENSOR_ACC to "MSG_SENSOR_LSM_ACC"

**Comment by tao-luke** [comment]
For the first question, I think the goal is to have the sensors report more information per minute than a normal status message. And that is done by having them refresh on a different constant, refer to sensor_general.h. 
For the other changes, what is your take? @BluCodeGH

**Comment by tao-luke** [comment]
also @KavinSatheeskumar Sorry if anything was unclear in my styling. slack me ANYTIME if needed :)

**Comment by KavinSatheeskumar** [comment]
Just a clarification on my first comment. I am suggesting lumping all of "last_baro_millis", "last_accel_millis" and so on into "last_update_millis" instead. I don't see any reason why we need them to be separate variables.

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
(this should be a discussion in a reviewable thread) we separate them because if we try to send all of those messages at once we fill up the CAN tx buffer and some get dropped. So by having slightly offset intervals we spread out when they get sent.

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_sensor/3#-:-N3e0uarAE7MDlrYZ2I1:b-juxri2)* status: all files reviewed, 5 unresolved discussions (waiting on @KavinSatheeskumar and @tao-luke)

___
*[`main.c` line 64 at r2](https://reviewable.io/reviews/waterloo-rocketry/cansw_sensor/3#-N3e1yyh2ohADtkjXVrV:-N3e1yyh2ohADtkjXVrW:bz2ostd) ([raw file](https://github.com/waterloo-rocketry/cansw_sensor/blob/751452830371621bfca661694b96f21d730995b1/main.c#L64)):*
> ```C
>     uint32_t last_baro_millis = millis();
>     uint32_t last_accel_millis = millis();
>     uint32_t last_accel2_millis = millis();
> ```

We should do something like `millis(); millis() + 25; millis() + 50;...` to offset when the messages get sent.



_Code quote:_
```C
    uint32_t last_baro_millis = millis();
    uint32_t last_accel_millis = millis();
    uint32_t last_accel2_millis = millis();
```
___
*[`main.c` line 137 at r2](https://reviewable.io/reviews/waterloo-rocketry/cansw_sensor/3#-N3W18bY5xDOXCvBm9Z3:-N3e1QG10Z2rQdJlorA6:b6jei3b) ([raw file](https://github.com/waterloo-rocketry/cansw_sensor/blob/751452830371621bfca661694b96f21d730995b1/main.c#L137)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

I know this will be kinda a bitch to change, but maybe MSG_SENSOR_ACC2 had ought be "MSG_SENSOR_MCU_ACC" instead. If we are feeling terribly bitchy, then possibly change MSG_SENSOR_ACC to "MSG_SENSOR_LSM_ACC"
</blockquote></details>

Not in scope at this point, also having it be generic is better for future boards with different models.

**Review by tao-luke — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_sensor/3)* status: all files reviewed, 5 unresolved discussions (waiting on @BluCodeGH and @KavinSatheeskumar)

___
*[`main.c` line 64 at r2](https://reviewable.io/reviews/waterloo-rocketry/cansw_sensor/3#-N3e1yyh2ohADtkjXVrV:-N3fRjRT63AotC5leEks:b-896fix) ([raw file](https://github.com/waterloo-rocketry/cansw_sensor/blob/751452830371621bfca661694b96f21d730995b1/main.c#L64)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

We should do something like `millis(); millis() + 25; millis() + 50;...` to offset when the messages get sent.
</blockquote></details>

Done.
___
*[`main.c` line 101 at r2](https://reviewable.io/reviews/waterloo-rocketry/cansw_sensor/3#-N3W2hM-2tb-mF_kNEdq:-N3fSf7oE2vqL4rwzJYG:b-tnn7vg) ([raw file](https://github.com/waterloo-rocketry/cansw_sensor/blob/751452830371621bfca661694b96f21d730995b1/main.c#L101)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

Kinda dumbass question, but is there any reason we are doing "last_baro_millis" and "last_accel_millis" if the code is going to function identically for all of them?
</blockquote></details>

refer to above. The different variables offset the queueing of sensor messages.
___
*[`main.c` line 116 at r2](https://reviewable.io/reviews/waterloo-rocketry/cansw_sensor/3#-N3W-IXF1ERTwAEDDu-m:-N3fRtZS7cK0nyb1DBZy:b-896fix) ([raw file](https://github.com/waterloo-rocketry/cansw_sensor/blob/751452830371621bfca661694b96f21d730995b1/main.c#L116)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

Took me a while to figure out that this was Magnetometer data. Might be worth a comment either here or somewhere else.
</blockquote></details>

Done.
___
*[`main.c` line 127 at r2](https://reviewable.io/reviews/waterloo-rocketry/cansw_sensor/3#-N3W1-B3-RdjY44ayFU2:-N3fT4tx-9JBKIfD7voi:b-d3zvvk) ([raw file](https://github.com/waterloo-rocketry/cansw_sensor/blob/751452830371621bfca661694b96f21d730995b1/main.c#L127)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

If we are changing this if-statement to send gyro-data as well as acceleration data, maybe we had ought change the name "last_accel2_millis" to something like "last_MPU_millis"
</blockquote></details>

refer to below for naming.
___
*[`main.c` line 137 at r2](https://reviewable.io/reviews/waterloo-rocketry/cansw_sensor/3#-N3W18bY5xDOXCvBm9Z3:-N3fT7tS0-ZowwndFbcm:b-896fix) ([raw file](https://github.com/waterloo-rocketry/cansw_sensor/blob/751452830371621bfca661694b96f21d730995b1/main.c#L137)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Not in scope at this point, also having it be generic is better for future boards with different models.
</blockquote></details>

Done.

**Pull request merged**
