### PR TITLE
Remove old IMU code

### PR DESCRIPTION
**Pull request by Darth-Raazi**
Out with the old, in with the new!

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_sensor/5)

### CODE REVIEW

**Comment by BluCodeGH** [comment]
I'd prefer to only merge a single PR for the new mini sensor changes so that everything can be reviewed together and we don't have a nonfunctional master branch between this PR and the next. Maybe merge into the other code branch instead?

**Comment by Darth-Raazi** [comment]
Sure, I'll resolve conflicts and then re-request a review

**Review by KavinSatheeskumar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_sensor/5)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @Artem-Sotnikov, @BluCodeGH, and @Darth-Raazi)

___
*[`main.c` line 143 at r3](https://reviewable.io/reviews/waterloo-rocketry/cansw_sensor/5#-NSSKHJD1_mtmLhiIVJT:-NSSKHJEACU_z73bewvZ:bmurzs3) ([raw file](https://github.com/waterloo-rocketry/cansw_sensor/blob/c549c88d9484e971f5342437e08853063f66ff95/main.c#L143)):*
> ```C
>         }
> #endif
> #if SENS_TIME_DIFF_ms
> ```

Why are we doing this with a pre-processor macro instead of an if-statement?

**Comment by rdakhil** [comment]
Ready for review now. I do have one question about the IMU implementation:

The ICM-20948 register ODR_ALIGN_EN allows us to enable ODR start-time alignment. I assume this means that the accel, gyro, and mag data will be sampled at the same time, but I could be wrong. If that is the case then would this be desirable, especially for the Kalman filter?

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Reading through the datasheet I'm not so convinced that is what that feature does. ODR seems to have something to do with the sample rate of the sensors and generating interrupts at that frequency.

> Reviewed 6 of 8 files at r1, 2 of 7 files at r3, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_sensor/5#-:-NSlB4ZS6ikBwj5uH16N:bjo4ypy)* status: all files reviewed, 4 unresolved discussions (waiting on @Artem-Sotnikov, @Darth-Raazi, and @KavinSatheeskumar)

___
*[`ICM-20948.c` line 20 at r4](https://reviewable.io/reviews/waterloo-rocketry/cansw_sensor/5#-NSlBjOP6CrhciuKreHE:-NSlBjOQ3_yvHhlQaj6p:bnjl56s) ([raw file](https://github.com/waterloo-rocketry/cansw_sensor/blob/8cb6724b165c50e4329e3c57abc7053627ba0565/ICM-20948.c#L20)):*
> ```C
> bool ICM_20948_init(uint8_t ICM_20948_addr_in, uint8_t AK09916_mag_addr_in) {
>     ICM_20948_addr = ICM_20948_addr_in;
>     AK09916_mag_addr = AK09916_mag_addr_in;
> ```

Why are we taking in addresses when we end up just setting them back to the default values when we call this from `main`?
___
*[`ICM-20948.c` line 141 at r4](https://reviewable.io/reviews/waterloo-rocketry/cansw_sensor/5#-NSlC5Kn9dq72BCc9cQP:-NSlC5Kn9dq72BCc9cQQ:bnc0hg5) ([raw file](https://github.com/waterloo-rocketry/cansw_sensor/blob/8cb6724b165c50e4329e3c57abc7053627ba0565/ICM-20948.c#L141)):*
> ```C
> bool ICM_20948_get_temp(int16_t *temp) {
>     ICM_20948_get_temp_raw(temp);
>     *temp /= 333.87;
> ```

Does this work? I feel like something might get losts in the implicit casts to/from uint16_t and float but idk.
___
*[`main.c` line 143 at r3](https://reviewable.io/reviews/waterloo-rocketry/cansw_sensor/5#-NSSKHJD1_mtmLhiIVJT:-NSlCoiICYTXzaZ8Lnm0:bltvtbn) ([raw file](https://github.com/waterloo-rocketry/cansw_sensor/blob/c549c88d9484e971f5342437e08853063f66ff95/main.c#L143)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

Why are we doing this with a pre-processor macro instead of an if-statement?
</blockquote></details>

It makes the zero case handling nice and easy /shrug.
___
*[`main.c` line 180 at r4](https://reviewable.io/reviews/waterloo-rocketry/cansw_sensor/5#-NSlCw279l1J5tEppgcB:-NSlCw279l1J5tEppgcC:b-csdxdf) ([raw file](https://github.com/waterloo-rocketry/cansw_sensor/blob/8cb6724b165c50e4329e3c57abc7053627ba0565/main.c#L180)):*
> ```C
> 
>         case MSG_LEDS_ON:
>             LED_ON_G();
> ```

We should turn all of the LEDs on/off.

**Review by BluCodeGH — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_sensor/5)* status: all files reviewed, 2 unresolved discussions (waiting on @Artem-Sotnikov, @Darth-Raazi, and @KavinSatheeskumar)

**Review by BluCodeGH — APPROVED** [review]
@KavinSatheeskumar please re-review.

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_sensor/5#-:-NUEfRxPBPBajTz3W4vj:b-uk2jvl)* status: all files reviewed, 1 unresolved discussion (waiting on @Artem-Sotnikov and @KavinSatheeskumar)

**Comment by BluCodeGH** [comment]
Closing since changes are included on minisensor-2023-cleanup branch

**Pull request closed without merging**
